### ISSUE TITLE
About .json to .npy

### ISSUE THREAD

**Issue by iluvrachel** [ChrisWu1997/2D-Motion-Retargeting#10]
Thank you for your excellent work!
The code fbx2joints3d.py convert .fbx files into .json format.
But only .npy format files could be recognized in the code preprocess.py and also the subsequent process. 
So how can I prepare my own dataset?
Or how can I convert json files to npy files like you did?

**Comment by ChrisWu1997** [comment]
Thanks for this issue! 
I forgot to upload that script. Now I add a function `json2npy` in `fbx2joints3d.py` to convert .json to .npy. Please check if that works since I haven't test it. Feel free to let me know if there is any problem.

**Comment by iluvrachel** [comment]
Thanks a lot!
