### ISSUE TITLE
How does two encoder model compare with three encoder model?

### ISSUE THREAD

**Issue by rozentill** [ChrisWu1997/2D-Motion-Retargeting#12]
Hi there,

Thank you for the great work! But I wonder why you trained three models but not only a three encoder model(full model). You can definitely transfer the motion and view using a three encoder model. Does two encoder model perform better on motion feature extraction?

Thanks!

**Comment by ChrisWu1997** [comment]
Thanks for your question. 

You are right about that the three encoder model can transfer both the skeleton and view. But if you only care about one of them, e.g. to retarget the skeleton in 2D, then it's unnecessary to get view angle involved. In that case, a two encoder model will have better performance.

**Comment by rozentill** [comment]
So what if I just want to extract motion feature, i.e. only **motion_encoder**, should I pick the two encoder version or three encoder version?  Which one would be better?

**Comment by ChrisWu1997** [comment]
It depends on how you define the "good" motion feature. But in general, I would suggest to use the three encoder version, since it yields skeleton-independent and view-independent motion representation.

**Comment by rozentill** [comment]
Okay, thank you so much!
