### ISSUE TITLE
训练出错

### ISSUE THREAD

**Issue by wwwjs** [ChrisWu1997/2D-Motion-Retargeting#16]
您好， 我用python3 train.py -n full -g 0来训练的时候，出现了下面的错误：
Traceback (most recent call last):
  File "train.py", line 101, in <module>
    main()
  File "train.py", line 39, in main
    train_loader = get_dataloader('train', config, config.batch_size, config.num_workers)
  File "/home/sjwang/python_project/2D-Motion-Retargeting-master/dataset/__init__.py", line 17, in get_dataloader
    num_workers=num_workers, worker_init_fn=lambda _: np.random.seed())
  File "/home/sjwang/py/python3/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 802, in __init__
    sampler = RandomSampler(dataset)
  File "/home/sjwang/py/python3/lib/python3.6/site-packages/torch/utils/data/sampler.py", line 64, in __init__
    "value, but got num_samples={}".format(self.num_samples))
ValueError: num_samples should be a positive integeral value, but got num_samples=0

应该怎么解决呢？

**Comment by ChrisWu1997** [comment]
请问有下载好数据并放在正确的目录下吗？

**Comment by wwwjs** [comment]
我是按照readme里面的说的下载的to download it, see Google Drive or Baidu Drive (8jq3). After downloading, extract it into ./mixamo_data.并放在了mixamo_data文件夹------------------ 原始邮件 ------------------
发件人: "Rundi Wu"<notifications@github.com>
发送时间: 2019年10月19日(星期六) 中午1:03
收件人: "ChrisWu1997/2D-Motion-Retargeting"<2D-Motion-Retargeting@noreply.github.com>;
抄送: "wwwjs"<253963563@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [ChrisWu1997/2D-Motion-Retargeting] 训练出错 (#16)



请问有下载好数据并放在正确的目录下吗？
 
&mdash;

**Comment by wwwjs** [comment]
十分感谢指导，问题已经解决了。原因是之前我把mixamo_data放在dataset里面处理的。再次感谢------------------ 原始邮件 ------------------
发件人: "Rundi Wu"<notifications@github.com>
发送时间: 2019年10月19日(星期六) 中午1:03
收件人: "ChrisWu1997/2D-Motion-Retargeting"<2D-Motion-Retargeting@noreply.github.com>;
抄送: "wwwjs"<253963563@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [ChrisWu1997/2D-Motion-Retargeting] 训练出错 (#16)



请问有下载好数据并放在正确的目录下吗？
 
&mdash;

**Comment by ChrisWu1997** [comment]
不客气

**Comment by ClaudiaShu** [comment]
你好！请问是怎么解决的呢？我是在Colab里面运行的代码，现在的文件结构是下面这样子的：
```
/mixamo_data
——/train
——/test
```
我同样尝试了直接在原文件下进行解压
```
/mixamo_data
——/mixamo_release
————/train
————/test
```
但同样找不到数据文件
期待您的回复

**Comment by ChrisWu1997** [comment]
您好，请问是跑`./dataset/preprocess.py`的时候出问题，还是跑`train.py`的时候出问题？上面一种文件组织应该是对的。

**Comment by ClaudiaShu** [comment]
> 您好，请问是跑`./dataset/preprocess.py`的时候出问题，还是跑`train.py`的时候出问题？上面一种文件组织应该是对的。

您好！实在不好意思，是我的理解出现了偏差，误以为您Google drive中的数据集是已经预处理好的数据集，preprocess和train都没有问题，十分感谢
