### ISSUE TITLE
Can this project be used for single frame? 

### ISSUE THREAD

**Issue by hungsing92** [ChrisWu1997/2D-Motion-Retargeting#18]
Hi Chris,
    Many thanks for your work!
    I face a problem that retargeting someone's face landmakrs by other person with different expression. Can this work be used for that? 
   And can this work be used for single-frame?
Best regards,

**Comment by ChrisWu1997** [comment]
Hi! Thanks for taking interests in our work! Unfortunately we do not support single frame.
