### ISSUE TITLE
Extract latent representation information?

### ISSUE THREAD

**Issue by chuanenlin** [ChrisWu1997/2D-Motion-Retargeting#20]
From Fig. 9, 10, 11 of the paper, I saw that clustering visualizes the latent spaces distributions (view, skeleton, motion).
I am wondering if it is possible to output the latent space data (e.g., camera-view angle in degrees of the subject for a specific frame)?

**Comment by ChrisWu1997** [comment]
Hi, there are functions to visualize latent codes in `cluster.py`. You can look into that code for your own need.

**Comment by chuanenlin** [comment]
Thanks for the reply.

I tried running `python cluster.py -n view` to test and received the following error:
`line 126, in get_cluster_data
    all_data = torch.stack(all_data, dim=0)
RuntimeError: expected a non-empty list of Tensors
`

Does this mean I first need to download the Mixamo dataset as described in `mixamo_download_script.java`, and if so, may I ask where should the .fbx files be saved and are there any specific formatting (e.g., of directory names) required?

**Comment by ChrisWu1997** [comment]
Yes, you miss the data. But there is no need to download the original `fbx`, we provide [processed data](https://github.com/ChrisWu1997/2D-Motion-Retargeting#prepare-data) for direct usage.
