### ISSUE TITLE
训练评估

### ISSUE THREAD

**Issue by AbbyRosewood** [ChrisWu1997/2D-Motion-Retargeting#22]
您好，我才入门深度学习，想向您请教一下在您的项目中怎么去实时显示训练的loss和accuracy等指标呢？
![TIM图片20200318161303](https://user-images.githubusercontent.com/57899426/76939454-60698c80-6933-11ea-9e3c-1aa7c9de8b33.png)
这是我加载的tensorboard，但是数据好像没办法加载进来

**Comment by ChrisWu1997** [comment]
您好，可以先检查一下logdir对不对？默认日志存储的位置应该是'train_log/log'。

**Comment by AbbyRosewood** [comment]
感谢，解决了。是由于文件位置索引错误的问题

**Comment by AbbyRosewood** [comment]
您好，还有一个问题想请教您一下，在您的网络结构设计中，`c1, c2`分别代表什么呢

**Comment by ChrisWu1997** [comment]
`c1`相当于是input channel, `c2`s是output channel

**Comment by AbbyRosewood** [comment]
十分感谢！我理解了
